name: Sinon[bot]
on:
  workflow_dispatch: {}
  label:
    types: [created, edited, deleted]
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  pull_request:
    branches: [main]
    types: [opened, closed, reopened, synchronize, labeled, unlabeled, edited, ready_for_review]
  release:
    types: [created, published]

concurrency: event-handle

jobs:
  sinon:
    name: Sinon[bot]
    runs-on: ubuntu-latest
    if: |
      (github.repository_owner == 'Katsute' || github.repository_owner == 'KatsuteDev') &&
      github.actor != 'Sinon-bot' &&
      github.actor != 'dependabot[bot]' &&
      github.actor != 'dependabot-preview[bot]'
    steps:
      - name: ðŸ“¤ Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: âœ” Handle Event
        uses: Katsute/Sinon-bot@main
        with:
          token: ${{ secrets.SINON }}
